# Generated by Django 5.0 on 2023-12-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_time', models.DateTimeField(verbose_name='time published')),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
